on:
  push:
    branches:
      - master

name: deploy-testnet

jobs:
  deploy-rinkeby:
      name: deploy-rinkeby
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
            version: nightly

        - name: Deploy to Rinkeby
          env:
            RINKEBY_RPC_URL: ${{ secrets.RINKEBY_RPC_URL }}
            TEST_DEPLOY_PK: ${{ secrets.TEST_DEPLOY_PK }}
            ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          run: sh deploy.sh
